<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Nicovogelaar\Paginator\Adapter\DoctrineAdapter'                  => __DIR__ . '/src/Adapter/DoctrineAdapter.php',
  'Nicovogelaar\Paginator\Adapter\AdapterInterface'                 => __DIR__ . '/src/Adapter/AdapterInterface.php',
  'Nicovogelaar\Paginator\View\Helper\PaginatorSortingHelper'       => __DIR__ . '/src/View/Helper/PaginatorSortingHelper.php',
  'Nicovogelaar\Paginator\View\Helper\PaginatorHelper'              => __DIR__ . '/src/View/Helper/PaginatorHelper.php',
  'Nicovogelaar\Paginator\Container\SortingContainer'               => __DIR__ . '/src/Container/SortingContainer.php',
  'Nicovogelaar\Paginator\Container\ParameterContainer'             => __DIR__ . '/src/Container/ParameterContainer.php',
  'Nicovogelaar\Paginator\Container\FilterContainer'                => __DIR__ . '/src/Container/FilterContainer.php',
  'Nicovogelaar\Paginator\Form\FilterFieldset'                      => __DIR__ . '/src/Form/FilterFieldset.php',
  'Nicovogelaar\Paginator\Form\FilterForm'                          => __DIR__ . '/src/Form/FilterForm.php',
  'Nicovogelaar\Paginator\Service\AbstractDoctrinePaginatorFactory' => __DIR__ . '/src/Service/AbstractDoctrinePaginatorFactory.php',
  'Nicovogelaar\Paginator\Exception'                                => __DIR__ . '/src/Exception.php',
  'Nicovogelaar\Paginator\Module'                                   => __DIR__ . '/src/Module.php',
  'Nicovogelaar\Paginator\Paginator'                                => __DIR__ . '/src/Paginator.php',
  'Nicovogelaar\Paginator\Listener\PaginatorListener'               => __DIR__ . '/src/Listener/PaginatorListener.php',
);
